// Writes static/version.json from the data checkout the app is built
// against, plus the app and queriton commits (#333). Called from a Vite
// plugin (vite.config.ts) so it runs however Vite starts — `npm run build`,
// `vite dev` from the launch config, the e2e webServer.
//
// It used to be a hard link to data-repo/data/version.json, a tracked file
// regenerated by hand — which nobody did, so the deployed About page said
// 300 tablets from an April commit while shipping 377.

import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import { buildVersionInfo } from '../data-repo/lib/version-info.js';

function gitHead(cwd: string): string {
	try {
		return execFileSync('git', ['rev-parse', 'HEAD'], { cwd }).toString().trim();
	} catch {
		return 'unknown';
	}
}

export interface VersionJsonOptions {
	/** Root of the data checkout (the directory holding `data/`). */
	dataRepoRoot: string;
	/** Root of the Explorer checkout. */
	appRoot: string;
	/** Where to write; normally `<appRoot>/static/version.json`. */
	outFile: string;
	now?: Date;
}

export function writeVersionJson({
	dataRepoRoot,
	appRoot,
	outFile,
	now = new Date(),
}: VersionJsonOptions): void {
	const info = {
		...buildVersionInfo(dataRepoRoot),
		build: {
			appCommit: gitHead(appRoot),
			queritonCommit: gitHead(path.join(appRoot, 'packages', 'queriton')),
			builtAt: now.toISOString(),
		},
	};
	// Unlink first. Older checkouts have static/version.json as a *hard link*
	// to the tracked data-repo/data/version.json, and writing through it would
	// silently rewrite that tracked file.
	fs.rmSync(outFile, { force: true });
	fs.writeFileSync(outFile, JSON.stringify(info, null, 2) + '\n');
}
